configuration:
  - Debug
  - Release

clone_depth: 1

platform:
  - Win32
  - x64

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  MSVC_DEFAULT_OPTIONS: ON
  BUILD: msvc

before_build:
 - mkdir build
 - cd build

build_script:
  - python ../support/appveyor-build.py

on_failure:
  - appveyor PushArtifact Testing/Temporary/LastTest.log
  - appveyor AddTest test

# Uncomment this to debug AppVeyor failures.
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
