name: lint

on:
  pull_request:
    paths:
      - '**.h'
      - '**.cc'

permissions:
  contents: read

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install clang-format
      run: |
        wget https://apt.llvm.org/llvm.sh
        sudo bash ./llvm.sh 21
        sudo apt install clang-format-21

    - name: Run clang-format
      run: |
        find include src -name '*.h' -o -name '*.cc' | \
          xargs clang-format-21 -i -style=file -fallback-style=none
        git diff --exit-code
